apiVersion: v1
kind: ServiceAccount
metadata:
  name: provisioning-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: provisioning-role
rules:
  - apiGroups: [""]
    resources: ["namespaces", "resourcequotas", "limitranges", "services", "pods"]
    verbs: ["get", "list", "create", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "create", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["get", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: provisioning-role-binding
subjects:
  - kind: ServiceAccount
    name: provisioning-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: provisioning-role
  apiGroup: rbac.authorization.k8s.io
